# Site settings
title: Xiaohong Chen
email: xiaohong.chen@pi2.network
description: Personal website of Xiaohong Chen

url: "https://xchen.page"
baseurl: ""

# Social
twitter_username: chenxiaohong
github_username: xc93

# Build settings
markdown: kramdown

# No theme - using custom CSS
plugins:
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - serve
  - README.md
